import { Layout } from "@/components/layout";
import "./globals.css";
import type { Metadata } from "next";
import { Kanit, Dosis } from "next/font/google";

const kan = Kanit({
  subsets: ["latin"],
  display: "swap",
  weight: "500",
  variable: "--font-kanit",
});

const dos = Dosis({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dosis",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${kan.variable} ${dos.variable}`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
